name: gem
description: Flutter Music Player App.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.012

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_links: ^3.4.2
  audio_service: ^0.18.7
  audiotagger: ^2.2.1
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.5
  dart_des: ^1.0.2
  device_info_plus: ^9.0.0
  file_picker: ^5.3.0
  custom_navigation_bar: ^0.8.2
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_displaymode: ^0.6.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  just_audio: ^0.9.28
  marquee: ^2.2.3
  material_design_icons_flutter: ^6.0.7096
  on_audio_query: ^2.6.1
  package_info_plus: ^4.0.0
  palette_generator: ^0.3.3+1
  iconsax: ^0.0.8
  google_fonts: ^4.0.4
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  receive_sharing_intent: ^1.4.5
  share_plus: ^7.0.0
  sliding_up_panel: ^2.0.0+1
  # Dont update staggered grid from 0.4.0
  flutter_staggered_grid_view: ^0.4.0
  supabase: ^1.8.0
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  youtube_explode_dart: ^1.12.0
  flutter_svg: ^2.0.5
  tab_indicator_styler: ^2.0.0
  auto_size_text: ^3.0.0
  spotify: ^0.11.0
  eva_icons_flutter: ^3.1.0
  font_awesome_flutter: ^10.2.1
  glassmorphism: ^3.0.0
  flutter_web_auth: ^0.5.0
  pkce: ^1.1.0+1
  intl: ^0.18.1
  shared_preferences: ^2.0.15
  overlapping_panels: ^0.0.3
  pool: ^1.5.1
  modal_bottom_sheet: ^2.1.2
  connection_status_bar: ^1.1.6
  flutter_bluetooth_serial: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    # Add assets to the application.
    - assets/
    - assets/svg/
    - assets/elements/

  fonts:
    - family: Avenir Next
      fonts:
        - asset: fonts/AvenirNext.otf  

