name: Check for outdated dependencies

on:
  schedule:
    - cron:  '0 0 * * *' # run every day at midnight

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Install the Flutter SDK
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      # Check for outdated dependencies
      - name: Check for outdated dependencies
        run: flutter pub outdated --precise
        id: outdated_deps
        env:
          FLUTTER_PUB_ENVIRONMENT: dev
      - name: Notify about outdated dependencies
        if: steps.outdated_deps.outputs.exit_code == 0
        uses: elgohr/Send-Me-A-Message@v1.8.0
        with:
          text: There are outdated dependencies in your Flutter project!
          subject: Outdated Dependencies


# This configuration file defines a workflow that runs every day at midnight using a cron schedule. 
# The workflow consists of a single job with three steps:

# The first step checks out the repository.
# The second step installs the Flutter SDK.
# The third step runs the flutter pub outdated command to check for outdated dependencies in the project. 
# If any outdated dependencies are found, the fourth step uses the elgohr/Send-Me-A-Message action to send you a notification about the outdated dependencies