# name: Build and Release

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     name: Build APK
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: "stable"

#       - name: Build APK
#         run: flutter build apk --release

#       - name: Archive Artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: APK
#           path: build/app/outputs/flutter-apk/app-release.apk
name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Build APK
        run: flutter build apk --release

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: APK
          path: app-release.apk

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: app-release.apk
          tag_name: v1.0.0
          # release_name: Release v1.0.0
          body: |
            Release v1.0.0
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
