name: Take screenshots

on:
  push:
    branches:
      - main

jobs:
  take_screenshots:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Install the Flutter SDK
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      # Get the list of supported devices
      - name: Get device list
        run: flutter devices

      # Take screenshots on each device
      - name: Take screenshots
        run: flutter drive --target=test_driver/screenshot.dart --screenshots
        env:
          FLUTTER_DRIVER_USE_FIRST_DEVICE: true
          FLUTTER_DRIVER_NO_ANIMATIONS: true

      # Create a new release
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload the screenshots to the release
      - name: Upload screenshots
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: screenshots/*
          asset_name: screenshots-${{ github.ref }}.zip
          asset_content_type: application/zip
